In [107]:
#Behzad Khadim
#SP20-BCS-019

#all sentences in the assignment 
from sklearn.feature_extraction.text import TfidfVectorizer
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from sklearn.feature_extraction.text import CountVectorizer
import pandas as pd
import math

sentence1 = 'sunshine state enjoy sunshine'
sentence2 = 'brown fox jump high, brown fox run'
sentence3 = 'sunshine state fox run fast'

corpus = [sentence1,sentence2,sentence3]
corpus

['sunshine state enjoy sunshine',
 'brown fox jump high, brown fox run',
 'sunshine state fox run fast']

In [108]:

vectorizer = CountVectorizer()

data = vectorizer.fit_transform(corpus)
headings = vectorizer.get_feature_names()
array = data.toarray()
print(headings)
print(data.toarray())


['brown', 'enjoy', 'fast', 'fox', 'high', 'jump', 'run', 'state', 'sunshine']
[[0 1 0 0 0 0 0 1 2]
 [2 0 0 2 1 1 1 0 0]
 [0 0 1 1 0 0 1 1 1]]


/usr/local/lib/python3.8/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


In [109]:
indexes = ['S1','S2','S3']

table = pd.DataFrame(array,columns = [headings],index= indexes)

table

brown enjoy fast fox high jump run state sunshine
S1     0     1    0   0    0    0   0     1        2
S2     2     0    0   2    1    1   1     0        0
S3     0     0    1   1    0    0   1     1        1

Term Frequency for the given sentences

In [110]:
def termf(sentence, wordbag):
    term_frequency_dictionary = {}
    length_of_wordbag = len(wordbag)

    for word, count in sentence.items():
        term_frequency_dictionary[word] = count / float(length_of_wordbag)

    return term_frequency_dictionary

In [111]:
dicS1 = table.iloc[0].to_dict()
bags1 = sentence1.split(" ")
tfs1 = termf(dicS1, bags1)

dicS2 = table.iloc[1].to_dict()
bags2 = sentence2.split(" ")
tfs2 = termf(dicS2, bags2)

dicS3 = table.iloc[2].to_dict()
bags3 = sentence3.split(" ")
tfs3 = termf(dicS3, bags3)


term_frequency = pd.DataFrame([tfs1,tfs2,tfs3], columns = [headings])
term_frequency

brown enjoy fast       fox      high      jump       run state sunshine
0  0.000000  0.25  0.0  0.000000  0.000000  0.000000  0.000000  0.25      0.5
1  0.285714  0.00  0.0  0.285714  0.142857  0.142857  0.142857  0.00      0.0
2  0.000000  0.00  0.2  0.200000  0.000000  0.000000  0.200000  0.20      0.2

invserse document frequency for the given sentences

In [112]:
def invserse(sentence):
    idfDict = {}
    N = len(sentence)
    
    idfDict = dict.fromkeys(sentence[0].keys(), 0)     # Idf 
    for doc in sentence:
        for word, val in doc.items():
            if val > 0:
                idfDict[word] += 1
    
    for word, val in idfDict.items():
        idfDict[word] = math.log10(N / float(val))
        
    return idfDict

In [113]:
iout = invserse([dicS1, dicS2, dicS3])

inverse = pd.DataFrame([iout],columns =[headings])
inverse

brown     enjoy      fast       fox      high      jump       run  \
0  0.477121  0.477121  0.477121  0.176091  0.477121  0.477121  0.176091   

      state  sunshine  
0  0.176091  0.176091

TF-IDF for the given data

In [114]:
def termandinverse(tfsentence, idfs):
    tfidf = {}
    for word, val in tfsentence.items():
        tfidf[word] = val*idfs[word]
    return tfidf

new1 = termandinverse(tfs1,iout)
new2 = termandinverse(tfs2,iout)
new3 = termandinverse(tfs3,iout)

tfidf = pd.DataFrame([new1,new2,new3], columns = [headings])
tfidf

brown    enjoy      fast       fox     high     jump       run     state  \
0  0.00000  0.11928  0.000000  0.000000  0.00000  0.00000  0.000000  0.044023   
1  0.13632  0.00000  0.000000  0.050312  0.06816  0.06816  0.025156  0.000000   
2  0.00000  0.00000  0.095424  0.035218  0.00000  0.00000  0.035218  0.035218   

   sunshine  
0  0.088046  
1  0.000000  
2  0.035218

In [115]:
import numpy as np
from numpy.linalg import norm

print("Sentence1:", sentence1)
print("Sentence3:", sentence3)

sentence_1 = np.array([0, 1, 0, 0, 0, 0, 0, 1, 2])
sentence_3 = np.array([0, 0, 1, 1, 0, 0, 1, 1, 1])

print("Vector1:", sentence_1)
print("Vector3:", sentence_3)


cosine = np.dot(sentence_1,sentence_3)/(norm(sentence_1)*norm(sentence_3))
print("Cosine Similarity Of The Two sentences:", cosine)


Sentence1: sunshine state enjoy sunshine
Sentence3: sunshine state fox run fast
Vector1: [0 1 0 0 0 0 0 1 2]
Vector3: [0 0 1 1 0 0 1 1 1]
Cosine Similarity Of The Two sentences: 0.5477225575051661
